# Generated by Django 4.2.7 on 2023-12-07 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meals.bookingrequest'),
        ),
    ]
