# Generated by Django 4.2.7 on 2023-12-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_bookings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
